port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
mode: rule
log-level: error
external-controller: 0.0.0.0:9090
secret: 123cxzzxc
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
interface-name: eth0
dns:
  enable: true
  ipv6: false
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 192.168.10.1
  - 223.5.5.5
  fallback:
  - tls://1.0.0.1:853
  - tls://8.8.4.4:853
  default-nameserver:
  - 192.168.10.1
  fake-ip-filter:
  - "+.*"
  enhanced-mode: fake-ip
profile:
  store-selected: true
authentication:
- rastyu:password
