port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
mode: rule
log-level: error
external-controller: 0.0.0.0:9090
secret: password
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
interface-name: eth0
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  fallback:
  - tls://1.0.0.1:853
  - tls://8.8.8.8:853
  default-nameserver:
  - 223.5.5.5
  - 192.168.10.1
profile:
  store-selected: true
authentication:
- rastyu:password
